### ISSUE TITLE
[question] Invalid slot name: "#<easy-lentic-el2org-configuration :lentic-file>" ...

### ISSUE THREAD

**Issue by tumashu** [phillord/lentic#47]
I use my own lentic extension: easy-lentic (https://github.com/tumashu/easy-lentic)

Now I find a issue, like:

```
Invalid slot name: "#<easy-lentic-el2org-configuration :lentic-file>", "e:/projects/emacs-packages/ox-latex-chinese/ox-latex-chinese.org"
```
I don't fimilar lentic's code, could you tell me how to debug and the possible place of quesion?

**Comment by phillord** [comment]
Difficult to say for sure. If you turn on debugging you should get a
stack trace.

The error in question is caused by calling "eieio-oset" on an object
which doesn't have that slot. :lentic-file is part of the default lentic
configuration, so that should be there for all forms of lentic config.

You need to find out where the error comes from, then have a look at the
config object before you call it!

**Comment by tumashu** [comment]
I use emacs git in my linux machine, it works well, the problem only can be found in window7,

```
This is GNU Emacs, a part of the GNU operating system.

GNU Emacs 24.5.1 (i686-pc-mingw32)
 of 2015-04-11 on LEG570
Copyright (C) 2015 Free Software Foundation, Inc.

```
Backtrack can't be pasted to here for special string:

[log.txt](https://github.com/phillord/lentic/files/276674/log.txt)

**Comment by phillord** [comment]
The log is in Chinese unfortunately. Can you tell me how to reproduce and I will look at it for you.

**Comment by tumashu** [comment]
Thanks for your help, I can reproduce the problem in window like this:
1. Install easy-lentic from melpa
2. Open a lenticify elisp file and run command `easy-lentic-switch-window'

**Comment by tumashu** [comment]
I have found the problem, thanks!

**Comment by phillord** [comment]
Good job -- sorry for slow feedback, got a lot on!
